# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jpsmith/git-repos/oversampled-pfb/vivado/myproj/project_1.srcs/sources_1/bd/os_pfb/ip/os_pfb_auto_ds_1/os_pfb_auto_ds_1.xci
# IP: The module: 'os_pfb_auto_ds_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jpsmith/git-repos/oversampled-pfb/vivado/myproj/project_1.srcs/sources_1/bd/os_pfb/ip/os_pfb_auto_ds_1/os_pfb_auto_ds_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'os_pfb_auto_ds_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/jpsmith/git-repos/oversampled-pfb/vivado/myproj/project_1.srcs/sources_1/bd/os_pfb/ip/os_pfb_auto_ds_1/os_pfb_auto_ds_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'os_pfb_auto_ds_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/jpsmith/git-repos/oversampled-pfb/vivado/myproj/project_1.srcs/sources_1/bd/os_pfb/ip/os_pfb_auto_ds_1/os_pfb_auto_ds_1.xci
# IP: The module: 'os_pfb_auto_ds_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jpsmith/git-repos/oversampled-pfb/vivado/myproj/project_1.srcs/sources_1/bd/os_pfb/ip/os_pfb_auto_ds_1/os_pfb_auto_ds_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'os_pfb_auto_ds_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/jpsmith/git-repos/oversampled-pfb/vivado/myproj/project_1.srcs/sources_1/bd/os_pfb/ip/os_pfb_auto_ds_1/os_pfb_auto_ds_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'os_pfb_auto_ds_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
