# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/os_pfb/os_pfb.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==os_pfb || ORIG_REF_NAME==os_pfb} -quiet] -quiet

# IP: bd/os_pfb/ip/os_pfb_axi_dma_0_0/os_pfb_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==os_pfb_axi_dma_0_0 || ORIG_REF_NAME==os_pfb_axi_dma_0_0} -quiet] -quiet

# IP: bd/os_pfb/ip/os_pfb_axi_smc_0/os_pfb_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==os_pfb_axi_smc_0 || ORIG_REF_NAME==os_pfb_axi_smc_0} -quiet] -quiet

# IP: bd/os_pfb/ip/os_pfb_os_pfb_0/os_pfb_os_pfb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==os_pfb_os_pfb_0 || ORIG_REF_NAME==os_pfb_os_pfb_0} -quiet] -quiet

# IP: bd/os_pfb/ip/os_pfb_xbar_0/os_pfb_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==os_pfb_xbar_0 || ORIG_REF_NAME==os_pfb_xbar_0} -quiet] -quiet

# IP: bd/os_pfb/ip/os_pfb_auto_ds_0/os_pfb_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==os_pfb_auto_ds_0 || ORIG_REF_NAME==os_pfb_auto_ds_0} -quiet] -quiet

# IP: bd/os_pfb/ip/os_pfb_auto_pc_0/os_pfb_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==os_pfb_auto_pc_0 || ORIG_REF_NAME==os_pfb_auto_pc_0} -quiet] -quiet

# IP: bd/os_pfb/ip/os_pfb_auto_ds_1/os_pfb_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==os_pfb_auto_ds_1 || ORIG_REF_NAME==os_pfb_auto_ds_1} -quiet] -quiet

# IP: bd/os_pfb/ip/os_pfb_auto_pc_1/os_pfb_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==os_pfb_auto_pc_1 || ORIG_REF_NAME==os_pfb_auto_pc_1} -quiet] -quiet

# IP: bd/os_pfb/ip/os_pfb_ps8_0_axi_periph_0/os_pfb_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==os_pfb_ps8_0_axi_periph_0 || ORIG_REF_NAME==os_pfb_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/os_pfb/ip/os_pfb_rst_ps8_0_99M_0/os_pfb_rst_ps8_0_99M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==os_pfb_rst_ps8_0_99M_0 || ORIG_REF_NAME==os_pfb_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/os_pfb/ip/os_pfb_zynq_ultra_ps_e_0_0/os_pfb_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==os_pfb_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==os_pfb_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: bd/os_pfb/os_pfb_ooc.xdc
